kind: Deployment
apiVersion: apps/v1beta1
metadata:
  name: microservice1-api
spec:
  replicas: 3
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      labels:
        app: microservice1-api
    spec:
      containers:
        - name: microservice1-api
          image: acrmaznaakspoc01.azurecr.io/akspoc/microservice1:v2
          ports:
          - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
---
kind: Service
apiVersion: v1
metadata:
  name: microservice1-api-ilb
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    service.beta.kubernetes.io/azure-load-balancer-internal-subnet: "snetmaznaaksfe01"
spec:
  type: LoadBalancer
  selector:
    app: microservice1-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80